# Generated by Django 3.2.16 on 2026-04-17 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="shop",
            name="industry_type",
            field=models.CharField(
                choices=[
                    ("BARBERSHOP", "Барбершоп"),
                    ("DENTISTRY", "Стоматология"),
                    ("BEAUTY_SALON", "Салон красоты"),
                    ("CLINIC", "Клиника"),
                    ("GENERIC", "Другое"),
                ],
                default="BARBERSHOP",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="shop",
            name="timezone",
            field=models.CharField(default="Asia/Almaty", max_length=64),
        ),
    ]
