# Generated by Django 3.2.16 on 2026-04-18 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_shop_industry_type_shop_timezone"),
    ]

    operations = [
        migrations.AddField(
            model_name="barber",
            name="fixed_salary_kzt",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
