# Generated by Django 3.2.16 on 2026-04-20 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_barber_fixed_salary_kzt"),
    ]

    operations = [
        migrations.AddField(
            model_name="shop",
            name="access_mode",
            field=models.CharField(
                choices=[
                    ("LEGACY", "Внутренний доступ"),
                    ("TRIAL", "Пробный доступ"),
                    ("SUBSCRIPTION", "Подписка"),
                ],
                default="LEGACY",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="shop",
            name="subscription_ends_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="shop",
            name="trial_ends_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
